/**
 * The only way this app talks to kayla-backend.
 *
 * Three things it exists to guarantee, each of which is a rule from agents.md rather than a
 * preference:
 *
 * 1. **Types come from the contract, never from hand-written interfaces.** agents.md §8.1: "The
 *    OpenAPI schema generated by FastAPI *is* the contract." Every request body, response body and
 *    path below is read out of `./generated.ts`, which `npm run codegen` regenerates from
 *    `kayla-backend/openapi.json` and the drift gate hashes. A backend field rename fails
 *    `tsc --noEmit` here instead of returning `undefined` in a browser.
 *
 * 2. **Every failure arrives as one typed `ApiError`.** agents.md §8.2 gives every non-2xx response
 *    a single shape, `{error: {code, message, details}}`. A caller branches on `error.code` — a
 *    stable machine-readable string — and never on message text, which is localised and will
 *    change. A transport failure and a body that is not an envelope are *also* normalised into an
 *    `ApiError`, so a caller has exactly one failure type to handle and `fetch`'s raw `TypeError`
 *    never escapes this module.
 *
 * 3. **The access token lives in memory and nowhere else, and the refresh token never enters this
 *    bundle at all.** See `SESSION` and `ActiveSession` below: the dashboard's durable credential
 *    lives in an `HttpOnly` cookie that only `POST /auth/session` can be presented with, and that
 *    endpoint answers with a 15-minute access token and nothing else. Every other request is
 *    `credentials: "omit"` and carries its authority on the `Authorization` header.
 */

import { env } from "@/env";

import type { components, paths } from "./generated";

/** The §8.2 envelope, straight from the contract. */
type ErrorEnvelope = components["schemas"]["ErrorEnvelope"];

/** What `POST /auth/login` and `POST /auth/refresh` both return. */
export type Session = components["schemas"]["SessionResponse"];

/** What `POST /auth/session` returns: an access token and its owner, and **no refresh token**. */
export type RestoredSession = components["schemas"]["RestoredSession"];

/** The caller's own account, as the API describes it. */
export type AuthenticatedUser = components["schemas"]["AuthenticatedUser"];

/**
 * What this app actually holds once signed in — deliberately **less** than `Session`.
 *
 * `SessionResponse.tokens` is a `TokenPair`, and a `TokenPair` carries a seven-day refresh token.
 * The dashboard has never had a use for one (it does not call `POST /auth/refresh`), and now that
 * the backend keeps the browser's copy in an `HttpOnly` cookie this app must not retain a second,
 * script-readable copy of it: an XSS that could read `getSession().tokens.refresh_token` would walk
 * away with exactly the durable credential the cookie design exists to deny it. So `setSession`
 * takes the whole wire shape and keeps only these fields; the refresh token is dropped on the floor
 * the moment it arrives.
 *
 * Shaped as `{tokens: {...}, user}` rather than flattened so that every existing
 * `session.tokens.access_token` call site reads the same as it always did. That is not laziness:
 * the fewer places this change touches, the smaller the chance one of them was the place that
 * mattered.
 */
export interface ActiveSession {
  readonly tokens: Omit<Session["tokens"], "refresh_token" | "refresh_expires_at">;
  readonly user: AuthenticatedUser;
}

/** The six roles of agents.md §6.1, as a type rather than six string literals at call sites. */
export type UserRole = components["schemas"]["UserRole"];

/**
 * Codes this module raises itself, for failures that never reached a §8.2 handler.
 *
 * They are deliberately outside the backend's code space (`kayla/**` raises none of these), so a
 * caller can tell "the server said no" from "we never got an answer" without inspecting `status`.
 */
export const CLIENT_ERROR_CODES = {
  /** The request never produced an HTTP response: offline, DNS, TLS, CORS, or aborted. */
  networkUnreachable: "network_unreachable",
  /** An HTTP response arrived, but its body was not JSON in the shape the contract promises. */
  responseNotUnderstood: "response_not_understood",
} as const;

export type ClientErrorCode = (typeof CLIENT_ERROR_CODES)[keyof typeof CLIENT_ERROR_CODES];

/**
 * Every failure this module can produce, including the ones that are not HTTP failures.
 *
 * `status` is 0 when no HTTP response was received at all — that is the one case where branching on
 * `status` is meaningful; everywhere else, branch on `code`.
 */
export class ApiError extends Error {
  /** HTTP status, or 0 when the request never reached the server. */
  readonly status: number;
  /** The §8.2 `error.code`, or one of `CLIENT_ERROR_CODES`. Branch on this. */
  readonly code: string;
  /** The §8.2 `error.details`. Structured and non-sensitive by contract; empty when absent. */
  readonly details: Readonly<Record<string, unknown>>;
  /** Parsed `Retry-After`, in seconds, when the server sent one (429 and 503 do). */
  readonly retryAfterSeconds: number | null;

  constructor(init: {
    status: number;
    code: string;
    message: string;
    details?: Record<string, unknown>;
    retryAfterSeconds?: number | null;
  }) {
    super(init.message);
    this.name = "ApiError";
    this.status = init.status;
    this.code = init.code;
    this.details = Object.freeze({ ...(init.details ?? {}) });
    this.retryAfterSeconds = init.retryAfterSeconds ?? null;
  }
}

/* -------------------------------------------------------------------------------------------
 * The session store
 * ---------------------------------------------------------------------------------------- */

/**
 * The signed-in session, held in a module-scoped variable and **nowhere else**.
 *
 * **Never `localStorage`, never `sessionStorage`, never a cookie this code can read.** This
 * dashboard is the surface that reads aggregate HR data for a whole organisation, so a single XSS
 * on any page of it would turn a token in web storage into a silent bulk export of that data — web
 * storage is readable by any script running on the origin, and it survives the tab that was
 * compromised. A variable in this module is reachable only by code in this bundle and dies with the
 * tab, which turns "steal the token" into "keep a foothold in a live page". That reasoning is
 * unchanged and is why the **access** token still lives here and only here.
 *
 * ---------------------------------------------------------------------------------------------
 * What changed, and why the old conclusion was too strong
 * ---------------------------------------------------------------------------------------------
 * This comment used to end: *a cookie would be worse still, the backend sets none, and a full page
 * reload therefore signs the user out.* The middle clause is now false and the first was too broad,
 * so here is the corrected version rather than a quiet deletion.
 *
 * The cost of "in memory only" was not small. An HR admin who reloaded — or followed a link out and
 * came back, or was reloaded by a deploy — was signed out mid-task, every time, because a browser
 * has no keychain to keep a refresh token in.
 *
 * The fix that was *rejected*: put the refresh token in an `HttpOnly` cookie and call
 * `POST /auth/refresh` on boot. `HttpOnly` stops a script **reading** a cookie; it does not stop a
 * script **spending** one. An XSS could call `fetch("/auth/refresh", {credentials: "include"})` and
 * read the seven-day, self-rotating refresh token out of the response body, where `TokenPair` makes
 * it a required field — turning today's worst case (a 15-minute token that dies with the tab) into
 * durable offline access. Strictly worse.
 *
 * What was built instead: the backend sets one cookie, scoped by `Path` to the single endpoint
 * `POST /auth/session`, which answers with an access token and **no refresh token** at all
 * (`RestoredSession` has nowhere to put one). So:
 *
 * - This module still never sees, stores or sends the refresh token. `setSession` drops it.
 * - Exactly three calls in this app opt into sending the cookie, one at a time and by name — see
 *   `sendSessionCookie` below. Every other request is `credentials: "omit"`, so no ambient
 *   authority reaches any data endpoint.
 * - An XSS's ceiling is unchanged: it can mint 15-minute tokens while the page it compromised is
 *   alive, exactly as it can today, and can exfiltrate nothing that outlives the tab.
 *
 * The worker app is still different, and deliberately so — `RAG.md` §12.3 puts its refresh token in
 * the OS Keychain/Keystore, and the backend refuses to set this cookie for a worker-audience
 * session precisely so React Native's cookie jar never becomes a second, worse home for one.
 */
let SESSION: ActiveSession | null = null;

/**
 * The one `POST /auth/session` currently in the air, if any — see `restoreSessionOnce`.
 *
 * Lives beside `SESSION` rather than in the hook that consumes it so that `clearSession` can drop
 * both together, and so that every test which already resets the session store resets this too.
 */
let inFlightRestore: Promise<ActiveSession | null> | null = null;

/**
 * Who to tell when `SESSION` changes — `src/lib/session.ts`'s `useAuthenticatedSession`, and
 * nothing else today.
 *
 * Exists for `updateSessionUser` (whitelabel Phase 2): `SESSION` is a plain module variable, not
 * React state, so mutating it in place — which is exactly what a Settings-page branding save does
 * while the dashboard is already mounted and showing the *old* name/logo — would otherwise be
 * invisible to whichever component last read `getSession()` into its own `useState`. `setSession`
 * and `clearSession` notify too, for the same reason, even though today's only subscriber already
 * happens to re-derive its state around both of those through other means (a fresh mount, or the
 * `useAuthenticatedSession` restore effect) — a second subscriber should not have to know that.
 */
const sessionListeners = new Set<() => void>();

function notifySessionChange(): void {
  for (const listener of sessionListeners) listener();
}

/** Subscribe to every `SESSION` change. Returns the unsubscribe function. */
export function subscribeToSessionChanges(listener: () => void): () => void {
  sessionListeners.add(listener);
  return () => {
    sessionListeners.delete(listener);
  };
}

/**
 * Adopt a session returned by `/auth/login`, `/auth/signup/set-password` or
 * `/orgs/signup/complete`. Memory only, and **minus the refresh token** — see `ActiveSession`.
 */
export function setSession(session: Session): void {
  SESSION = {
    // Field by field rather than a spread, so that a refresh token cannot be re-admitted by a
    // future backend field this code never looked at.
    tokens: {
      access_token: session.tokens.access_token,
      token_type: session.tokens.token_type,
      expires_in: session.tokens.expires_in,
      expires_at: session.tokens.expires_at,
    },
    user: session.user,
  };
  notifySessionChange();
}

/** The current session, or null when signed out. */
export function getSession(): ActiveSession | null {
  return SESSION;
}

/**
 * Patch fields of the signed-in user in place, without touching `tokens`.
 *
 * Exists for the whitelabel branding surface: `org-branding-step.tsx` (the onboarding step) and
 * `(dashboard)/settings/page.tsx`'s Branding section both write `org_name`/`org_logo_url` through
 * `PATCH`/`POST .../logo/confirm`, and the response is the new source of truth for those two
 * fields — but the session in memory was built from an earlier `/auth/me` or signup response and
 * has no way to learn about it on its own. Without this, the sidebar and the dashboard tab title
 * would keep showing the *previous* name/logo (or the Kayla default) until the next full session
 * restore, which is exactly the "immediately see it reflected... without needing to re-login" gap
 * the whitelabel PRD's Phase 2 acceptance criteria calls out by name.
 *
 * A no-op when there is no session to patch — a save that outraces a sign-out has nothing left to
 * update, and that is not this function's failure to report.
 */
export function updateSessionUser(patch: Partial<AuthenticatedUser>): void {
  if (SESSION === null) return;
  SESSION = { tokens: SESSION.tokens, user: { ...SESSION.user, ...patch } };
  notifySessionChange();
}

/**
 * Forget the session. Called on sign-out, and whenever a credential must not be kept.
 *
 * Also drops any restore still in flight (see `restoreSessionOnce`). Forgetting the session and
 * then adopting the answer to a question asked before it was forgotten would sign a person back
 * in a moment after they pressed "Sign out".
 */
export function clearSession(): void {
  SESSION = null;
  inFlightRestore = null;
  notifySessionChange();
}

/**
 * Ask the backend to restore a session from its `HttpOnly` cookie, and adopt it.
 *
 * The one call in this app that boots a session without a password. It resolves to the restored
 * session on success and to `null` when there is nothing to restore — a first visit, a cleared
 * cookie jar, an expired or already-spent cookie — because "not signed in" is an ordinary outcome
 * of asking, not a failure worth throwing over. Anything that is *not* an authentication answer
 * (the API is unreachable, a proxy returned HTML) also resolves to `null`: the caller's only
 * sensible response to either is to show the sign-in page.
 *
 * This is the only call that sends the cookie in order to *obtain* a credential, and the response
 * it adopts carries no refresh token, so nothing durable enters this bundle's memory.
 */
export async function restoreSession(options: RequestOptions = {}): Promise<ActiveSession | null> {
  // Deliberately not sent with the current access token even if one exists: this call is about the
  // cookie, and `apiRequest` attaching a bearer header would make an expired token look like the
  // reason a restore failed.
  try {
    const restored = await apiRequest("post", "/auth/session", {
      ...options,
      sendSessionCookie: true,
    });
    SESSION = {
      tokens: {
        access_token: restored.access_token,
        token_type: restored.token_type,
        expires_in: restored.expires_in,
        expires_at: restored.expires_at,
      },
      user: restored.user,
    };
    notifySessionChange();
    return SESSION;
  } catch {
    clearSession();
    return null;
  }
}

/**
 * `restoreSession`, but at most one request at a time.
 *
 * --------------------------------------------------------------------------------------------
 * What this exists to stop, and what it used to be
 * --------------------------------------------------------------------------------------------
 * `POST /auth/session` spends a single-use cookie, so calling it twice means the second call
 * presents a token the first already spent — which the backend reads, correctly, as a stolen
 * token and answers by revoking the whole refresh family. Exactly one call is correctness, not
 * an optimisation.
 *
 * That was previously enforced in `useAuthenticatedSession` with a `useRef(false)` guard that
 * made the *second* caller do nothing at all. Under React Strict Mode — which `next dev` turns
 * on — that deadlocked the dashboard:
 *
 *   mount        -> guard set, restore starts
 *   cleanup      -> the first subscriber marks itself dead (Strict Mode's simulated unmount)
 *   mount again  -> guard already set, so this mount subscribes to nothing
 *   restore ends -> the only subscriber left is the dead one, so no state update ever happens
 *
 * The dashboard sat on "Loading your dashboard…" forever in `npm run dev`, while the production
 * build was fine because Strict Mode does not double-invoke there. The test suite could not see
 * it either: `@testing-library/react` does not render in Strict Mode.
 *
 * Deduplicating the promise instead keeps the one-request guarantee and lets every caller learn
 * how it ended. The second mount joins the request already in flight rather than starting
 * another or subscribing to nothing.
 *
 * The slot is released once the request settles, so a later attempt — after a restore that found
 * no cookie, say — asks again rather than replaying a stale answer for the life of the tab.
 */
export function restoreSessionOnce(options: RequestOptions = {}): Promise<ActiveSession | null> {
  inFlightRestore ??= restoreSession(options).finally(() => {
    inFlightRestore = null;
  });
  return inFlightRestore;
}

/* -------------------------------------------------------------------------------------------
 * Contract-derived types
 * ---------------------------------------------------------------------------------------- */

/** Pulls the JSON body out of a generated request-body or response entry. */
type JsonBody<T> = T extends { content: { "application/json": infer B } } ? B : never;

/** Statuses the contract uses for success. A 204 has no JSON body and resolves to `never`. */
type SuccessStatus = 200 | 201 | 202;

type OperationOf<P extends keyof paths, M extends keyof paths[P]> = paths[P][M];

/** The JSON request body of an operation, or `never` when it takes none. */
type RequestBodyOf<O> = O extends { requestBody: infer R } ? JsonBody<R> : never;

/** The JSON body of whichever success status the operation declares. */
type SuccessBodyOf<O> = O extends { responses: infer R }
  ? { [S in SuccessStatus & keyof R]: JsonBody<R[S]> }[SuccessStatus & keyof R]
  : never;

/** Paths that declare the given method. `paths` types an absent method as `never`, so this filters. */
type PathsWith<M extends string> = {
  [P in keyof paths]: paths[P] extends Record<M, object> ? P : never;
}[keyof paths];

/**
 * Generous but finite. Without it a request that never answers leaves a submit button spinning
 * forever; with it the caller gets an `ApiError` it already knows how to render. Not a design
 * value, so R5 does not apply.
 */
const REQUEST_TIMEOUT_MS = 15_000;

/** `NEXT_PUBLIC_API_BASE_URL` is validated as an absolute URL in `src/env.ts`; strip any trailing `/`. */
const API_ROOT = env.NEXT_PUBLIC_API_BASE_URL.replace(/\/+$/, "");

interface RequestOptions {
  /** Aborts the request. Composed with the built-in timeout. */
  readonly signal?: AbortSignal;
  /**
   * Send and accept the backend's `HttpOnly` session cookie on **this call only**.
   *
   * Defaults to `false`, and the default is the security property: `credentials: "omit"` means the
   * browser neither attaches a cookie nor stores a `Set-Cookie`, so no request this app makes
   * carries ambient authority and every authenticated call is authorised by the `Authorization`
   * header alone. An `apiRequest` that opted everything in would hand a durable credential to
   * `GET /dashboard/overview` and to every other data endpoint, which is exactly the CSRF surface
   * `SameSite=Strict` and the cookie's narrow `Path` are there to close.
   *
   * Exactly three calls set it, and each one needs it for a different half of the same cookie:
   *
   * - `POST /auth/login` and `POST /orgs/signup/complete` — to **receive** it. `credentials:
   *   "omit"` makes the browser ignore `Set-Cookie` outright, so without this the cookie would be
   *   set by the server and silently discarded by the client, and reload-restore would fail with
   *   nothing anywhere saying why.
   * - `POST /auth/session` — to **present** it. This is the only endpoint the cookie's `Path`
   *   allows it to be attached to at all.
   * - `POST /auth/logout` — to accept the expiry that clears it.
   *
   * Do not add a fourth without reading `kayla.auth.cookies`' module docstring first.
   */
  readonly sendSessionCookie?: boolean;
}

function isErrorEnvelope(value: unknown): value is ErrorEnvelope {
  if (typeof value !== "object" || value === null) return false;
  const { error } = value as { error?: unknown };
  if (typeof error !== "object" || error === null) return false;
  const { code, message } = error as { code?: unknown; message?: unknown };
  return typeof code === "string" && typeof message === "string";
}

/** `Retry-After` is either a delta in seconds or an HTTP date. Both are turned into seconds. */
function parseRetryAfter(header: string | null): number | null {
  if (header === null) return null;
  const trimmed = header.trim();
  if (trimmed === "") return null;

  const seconds = Number(trimmed);
  if (Number.isFinite(seconds)) return Math.max(0, Math.round(seconds));

  const at = Date.parse(trimmed);
  if (Number.isNaN(at)) return null;
  return Math.max(0, Math.round((at - Date.now()) / 1000));
}

/**
 * Turn a non-2xx response into an `ApiError`.
 *
 * Every error the backend renders goes through `kayla.errors.error_response`, so the envelope is
 * the expected case. The fallback exists for the responses that never reach application code at
 * all — a proxy's own 502 page, or a gateway timeout — which are HTML, not JSON.
 */
async function toApiError(response: Response): Promise<ApiError> {
  const retryAfterSeconds = parseRetryAfter(response.headers.get("Retry-After"));

  let body: unknown;
  try {
    body = await response.json();
  } catch {
    body = undefined;
  }

  if (isErrorEnvelope(body)) {
    return new ApiError({
      status: response.status,
      code: body.error.code,
      message: body.error.message,
      details: body.error.details,
      retryAfterSeconds,
    });
  }

  return new ApiError({
    status: response.status,
    code: CLIENT_ERROR_CODES.responseNotUnderstood,
    // Deliberately says nothing about the body. An upstream error page can contain anything, and
    // pasting it into the UI is how a stack trace reaches a user (§8.2).
    message: `The server responded with ${response.status} and a body this client does not understand.`,
    retryAfterSeconds,
  });
}

function timeoutSignal(caller: AbortSignal | undefined): AbortSignal {
  const timeout = AbortSignal.timeout(REQUEST_TIMEOUT_MS);
  return caller === undefined ? timeout : AbortSignal.any([caller, timeout]);
}

/**
 * Perform one request against the contract.
 *
 * `method` and `path` are checked against the generated `paths`, so `apiRequest("post", "/auth/me")`
 * does not compile and neither does a login body with a misspelled field.
 *
 * `"patch"` was added for P11's `PATCH /dashboard/settings` (agents.md §10.11 task 10) — the first
 * partial-update route this dashboard calls. Nothing above this line needed to change: the generic
 * plumbing (`OperationOf`, `RequestBodyOf`, `SuccessBodyOf`, `PathsWith`) already reads whichever
 * method key the caller names out of the generated `paths[P]`, so widening this union is the whole
 * change.
 */
export async function apiRequest<
  M extends "get" | "post" | "patch",
  P extends PathsWith<M> & keyof paths,
>(
  method: M,
  path: P,
  options: RequestOptions &
    (RequestBodyOf<OperationOf<P, M & keyof paths[P]>> extends never
      ? { body?: undefined }
      : { body: RequestBodyOf<OperationOf<P, M & keyof paths[P]>> }),
): Promise<SuccessBodyOf<OperationOf<P, M & keyof paths[P]>>> {
  const headers: Record<string, string> = { Accept: "application/json" };

  const session = getSession();
  if (session !== null) {
    headers.Authorization = `Bearer ${session.tokens.access_token}`;
  }

  const { body, signal, sendSessionCookie } = options as {
    body?: unknown;
    signal?: AbortSignal;
    sendSessionCookie?: boolean;
  };
  if (body !== undefined) {
    headers["Content-Type"] = "application/json";
  }

  let response: Response;
  try {
    response = await fetch(`${API_ROOT}${String(path)}`, {
      method: method.toUpperCase(),
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
      // `"omit"` unless this one call asked otherwise, and `"omit"` is what keeps agents.md §6.2
      // layer 1 on the token rather than on the browser's willingness to attach something. The
      // opt-in is per call and by name — see `RequestOptions.sendSessionCookie` for the three that
      // take it and why a blanket `"include"` would be a CSRF surface on every data endpoint.
      credentials: sendSessionCookie === true ? "include" : "omit",
      signal: timeoutSignal(signal),
    });
  } catch (cause) {
    throw new ApiError({
      status: 0,
      code: CLIENT_ERROR_CODES.networkUnreachable,
      message: "Could not reach the Kayla API.",
      details: { cause: cause instanceof Error ? cause.name : "unknown" },
    });
  }

  if (!response.ok) {
    throw await toApiError(response);
  }

  try {
    return (await response.json()) as SuccessBodyOf<OperationOf<P, M & keyof paths[P]>>;
  } catch {
    throw new ApiError({
      status: response.status,
      code: CLIENT_ERROR_CODES.responseNotUnderstood,
      message: "The server responded with a body this client does not understand.",
    });
  }
}
