/**
 * The only way this app talks to kayla-backend.
 *
 * Three things it exists to guarantee, each of which is a rule from agents.md rather than a
 * preference:
 *
 * 1. **Types come from the contract, never from hand-written interfaces.** agents.md §8.1: "The
 *    OpenAPI schema generated by FastAPI *is* the contract." Every request body, response body and
 *    path below is read out of `./generated.ts`, which `npm run codegen` regenerates from
 *    `kayla-backend/openapi.json` and the drift gate hashes. A backend field rename fails
 *    `tsc --noEmit` here instead of returning `undefined` in a browser.
 *
 * 2. **Every failure arrives as one typed `ApiError`.** agents.md §8.2 gives every non-2xx response
 *    a single shape, `{error: {code, message, details}}`. A caller branches on `error.code` — a
 *    stable machine-readable string — and never on message text, which is localised and will
 *    change. A transport failure and a body that is not an envelope are *also* normalised into an
 *    `ApiError`, so a caller has exactly one failure type to handle and `fetch`'s raw `TypeError`
 *    never escapes this module.
 *
 * 3. **The access token lives in memory and nowhere else.** See `SESSION` below.
 */

import { env } from "@/env";

import type { components, paths } from "./generated";

/** The §8.2 envelope, straight from the contract. */
type ErrorEnvelope = components["schemas"]["ErrorEnvelope"];

/** What `POST /auth/login` and `POST /auth/refresh` both return. */
export type Session = components["schemas"]["SessionResponse"];

/** The caller's own account, as the API describes it. */
export type AuthenticatedUser = components["schemas"]["AuthenticatedUser"];

/** The six roles of agents.md §6.1, as a type rather than six string literals at call sites. */
export type UserRole = components["schemas"]["UserRole"];

/**
 * Codes this module raises itself, for failures that never reached a §8.2 handler.
 *
 * They are deliberately outside the backend's code space (`kayla/**` raises none of these), so a
 * caller can tell "the server said no" from "we never got an answer" without inspecting `status`.
 */
export const CLIENT_ERROR_CODES = {
  /** The request never produced an HTTP response: offline, DNS, TLS, CORS, or aborted. */
  networkUnreachable: "network_unreachable",
  /** An HTTP response arrived, but its body was not JSON in the shape the contract promises. */
  responseNotUnderstood: "response_not_understood",
} as const;

export type ClientErrorCode = (typeof CLIENT_ERROR_CODES)[keyof typeof CLIENT_ERROR_CODES];

/**
 * Every failure this module can produce, including the ones that are not HTTP failures.
 *
 * `status` is 0 when no HTTP response was received at all — that is the one case where branching on
 * `status` is meaningful; everywhere else, branch on `code`.
 */
export class ApiError extends Error {
  /** HTTP status, or 0 when the request never reached the server. */
  readonly status: number;
  /** The §8.2 `error.code`, or one of `CLIENT_ERROR_CODES`. Branch on this. */
  readonly code: string;
  /** The §8.2 `error.details`. Structured and non-sensitive by contract; empty when absent. */
  readonly details: Readonly<Record<string, unknown>>;
  /** Parsed `Retry-After`, in seconds, when the server sent one (429 and 503 do). */
  readonly retryAfterSeconds: number | null;

  constructor(init: {
    status: number;
    code: string;
    message: string;
    details?: Record<string, unknown>;
    retryAfterSeconds?: number | null;
  }) {
    super(init.message);
    this.name = "ApiError";
    this.status = init.status;
    this.code = init.code;
    this.details = Object.freeze({ ...(init.details ?? {}) });
    this.retryAfterSeconds = init.retryAfterSeconds ?? null;
  }
}

/* -------------------------------------------------------------------------------------------
 * The session store
 * ---------------------------------------------------------------------------------------- */

/**
 * The signed-in session, held in a module-scoped variable and **nowhere else**.
 *
 * **Never `localStorage`, never `sessionStorage`, never a cookie.** This dashboard is the surface
 * that reads aggregate HR data for a whole organisation, so a single XSS on any page of it would
 * turn a token in web storage into a silent bulk export of that data — web storage is readable by
 * any script running on the origin, and it survives the tab that was compromised. A variable in
 * this module is reachable only by code in this bundle and dies with the tab, which turns
 * "steal the token" into "keep a foothold in a live page".
 *
 * A cookie would be worse still, not better: the browser would attach it to every request on its
 * own, which is precisely the ambient authority CSRF exploits. The backend sets no cookie for the
 * same reason (`kayla.auth.schemas` module docstring) and expects `Authorization: Bearer`.
 *
 * The cost is honest and accepted: a full page reload signs the user out, because the refresh
 * token has no safe browser home either. The worker app is different — `RAG.md` §12.3 puts its
 * refresh token in the OS Keychain/Keystore, which a browser does not have.
 */
let SESSION: Session | null = null;

/** Adopt a session returned by `/auth/login` or `/auth/refresh`. Memory only — see `SESSION`. */
export function setSession(session: Session): void {
  SESSION = session;
}

/** The current session, or null when signed out. */
export function getSession(): Session | null {
  return SESSION;
}

/** Forget the session. Called on sign-out, and whenever a credential must not be kept. */
export function clearSession(): void {
  SESSION = null;
}

/* -------------------------------------------------------------------------------------------
 * Contract-derived types
 * ---------------------------------------------------------------------------------------- */

/** Pulls the JSON body out of a generated request-body or response entry. */
type JsonBody<T> = T extends { content: { "application/json": infer B } } ? B : never;

/** Statuses the contract uses for success. A 204 has no JSON body and resolves to `never`. */
type SuccessStatus = 200 | 201 | 202;

type OperationOf<P extends keyof paths, M extends keyof paths[P]> = paths[P][M];

/** The JSON request body of an operation, or `never` when it takes none. */
type RequestBodyOf<O> = O extends { requestBody: infer R } ? JsonBody<R> : never;

/** The JSON body of whichever success status the operation declares. */
type SuccessBodyOf<O> = O extends { responses: infer R }
  ? { [S in SuccessStatus & keyof R]: JsonBody<R[S]> }[SuccessStatus & keyof R]
  : never;

/** Paths that declare the given method. `paths` types an absent method as `never`, so this filters. */
type PathsWith<M extends string> = {
  [P in keyof paths]: paths[P] extends Record<M, object> ? P : never;
}[keyof paths];

/**
 * Generous but finite. Without it a request that never answers leaves a submit button spinning
 * forever; with it the caller gets an `ApiError` it already knows how to render. Not a design
 * value, so R5 does not apply.
 */
const REQUEST_TIMEOUT_MS = 15_000;

/** `NEXT_PUBLIC_API_BASE_URL` is validated as an absolute URL in `src/env.ts`; strip any trailing `/`. */
const API_ROOT = env.NEXT_PUBLIC_API_BASE_URL.replace(/\/+$/, "");

interface RequestOptions {
  /** Aborts the request. Composed with the built-in timeout. */
  readonly signal?: AbortSignal;
}

function isErrorEnvelope(value: unknown): value is ErrorEnvelope {
  if (typeof value !== "object" || value === null) return false;
  const { error } = value as { error?: unknown };
  if (typeof error !== "object" || error === null) return false;
  const { code, message } = error as { code?: unknown; message?: unknown };
  return typeof code === "string" && typeof message === "string";
}

/** `Retry-After` is either a delta in seconds or an HTTP date. Both are turned into seconds. */
function parseRetryAfter(header: string | null): number | null {
  if (header === null) return null;
  const trimmed = header.trim();
  if (trimmed === "") return null;

  const seconds = Number(trimmed);
  if (Number.isFinite(seconds)) return Math.max(0, Math.round(seconds));

  const at = Date.parse(trimmed);
  if (Number.isNaN(at)) return null;
  return Math.max(0, Math.round((at - Date.now()) / 1000));
}

/**
 * Turn a non-2xx response into an `ApiError`.
 *
 * Every error the backend renders goes through `kayla.errors.error_response`, so the envelope is
 * the expected case. The fallback exists for the responses that never reach application code at
 * all — a proxy's own 502 page, or a gateway timeout — which are HTML, not JSON.
 */
async function toApiError(response: Response): Promise<ApiError> {
  const retryAfterSeconds = parseRetryAfter(response.headers.get("Retry-After"));

  let body: unknown;
  try {
    body = await response.json();
  } catch {
    body = undefined;
  }

  if (isErrorEnvelope(body)) {
    return new ApiError({
      status: response.status,
      code: body.error.code,
      message: body.error.message,
      details: body.error.details,
      retryAfterSeconds,
    });
  }

  return new ApiError({
    status: response.status,
    code: CLIENT_ERROR_CODES.responseNotUnderstood,
    // Deliberately says nothing about the body. An upstream error page can contain anything, and
    // pasting it into the UI is how a stack trace reaches a user (§8.2).
    message: `The server responded with ${response.status} and a body this client does not understand.`,
    retryAfterSeconds,
  });
}

function timeoutSignal(caller: AbortSignal | undefined): AbortSignal {
  const timeout = AbortSignal.timeout(REQUEST_TIMEOUT_MS);
  return caller === undefined ? timeout : AbortSignal.any([caller, timeout]);
}

/**
 * Perform one request against the contract.
 *
 * `method` and `path` are checked against the generated `paths`, so `apiRequest("post", "/auth/me")`
 * does not compile and neither does a login body with a misspelled field.
 */
export async function apiRequest<
  M extends "get" | "post",
  P extends PathsWith<M> & keyof paths,
>(
  method: M,
  path: P,
  options: RequestOptions &
    (RequestBodyOf<OperationOf<P, M & keyof paths[P]>> extends never
      ? { body?: undefined }
      : { body: RequestBodyOf<OperationOf<P, M & keyof paths[P]>> }),
): Promise<SuccessBodyOf<OperationOf<P, M & keyof paths[P]>>> {
  const headers: Record<string, string> = { Accept: "application/json" };

  const session = getSession();
  if (session !== null) {
    headers.Authorization = `Bearer ${session.tokens.access_token}`;
  }

  const { body, signal } = options as { body?: unknown; signal?: AbortSignal };
  if (body !== undefined) {
    headers["Content-Type"] = "application/json";
  }

  let response: Response;
  try {
    response = await fetch(`${API_ROOT}${String(path)}`, {
      method: method.toUpperCase(),
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
      // No cookie is ever sent or accepted. The backend sets none, and omitting them removes the
      // ambient authority that CSRF depends on (agents.md §6.2 layer 1 lives on the token, not on
      // the browser's willingness to attach one).
      credentials: "omit",
      signal: timeoutSignal(signal),
    });
  } catch (cause) {
    throw new ApiError({
      status: 0,
      code: CLIENT_ERROR_CODES.networkUnreachable,
      message: "Could not reach the Kayla API.",
      details: { cause: cause instanceof Error ? cause.name : "unknown" },
    });
  }

  if (!response.ok) {
    throw await toApiError(response);
  }

  try {
    return (await response.json()) as SuccessBodyOf<OperationOf<P, M & keyof paths[P]>>;
  } catch {
    throw new ApiError({
      status: response.status,
      code: CLIENT_ERROR_CODES.responseNotUnderstood,
      message: "The server responded with a body this client does not understand.",
    });
  }
}
